### ISSUE TITLE
Issue:

### ISSUE THREAD

**Issue by peterbabic** [yaegassy/coc-psalm#11]
On some projects `coc-psalm` works without an issue. However, on other projects, this error is shown right after the file is opened:
```
[coc.nvim]: UnhandledRejection: Cannot call write after a stream was destroyed        
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed          
    at new NodeError (node:internal/errors:371:5)                                     
    at _write (node:internal/streams/writable:321:11)                                 
    at Socket.Writable.write (node:internal/streams/writable:334:10)                  
    at /home/peterbabic/.vim/plugged/coc.nvim/build/index.js:34:3107                  
    at new Promise (<anonymous>)                                                      
    at qM.write (/home/peterbabic/.vim/plugged/coc.nvim/build/index.js:34:3028)       
    at HC.doWrite (/home/peterbabic/.vim/plugged/coc.nvim/build/index.js:35:1698)     
    at /home/peterbabic/.vim/plugged/coc.nvim/build/index.js:35:1597
```

![image](https://user-images.githubusercontent.com/3952052/155984680-3742205d-812c-4802-9da2-0ad69e9d090c.png)

**Comment by yaegassy** [comment]
I have never encountered this error in my environment, but maybe it happens in large projects. Or it could be that the psalm plugin is affecting it.

Is there a project repository or something that can reproduce this problem?

**Comment by peterbabic** [comment]
It is unfortunately not a public repository. We can close with the agreement that if I gather more details, I'll fill them in and reopen. Agree?
